---
# Database password — shared by all services connecting to postgres
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-password
  namespace: circleguard-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: db-password
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: cg-db-password-dev
---
# JWT signing secret — auth-service and gateway-service
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jwt-secret
  namespace: circleguard-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: jwt-secret
    creationPolicy: Owner
  data:
    - secretKey: secret
      remoteRef:
        key: cg-jwt-secret-dev
---
# Mail credentials — notification-service
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mail-credentials
  namespace: circleguard-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: mail-credentials
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: cg-mail-password-dev
