apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: kill-notification-service
  namespace: chaos-testing
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - circleguard-dev
    labelSelectors:
      app: notification-service
  duration: "60s"
