---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-password
  namespace: circleguard-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: db-password
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: cg-db-password-prod
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jwt-secret
  namespace: circleguard-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: jwt-secret
    creationPolicy: Owner
  data:
    - secretKey: secret
      remoteRef:
        key: cg-jwt-secret-prod
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qr-secret
  namespace: circleguard-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: qr-secret
    creationPolicy: Owner
  data:
    - secretKey: secret
      remoteRef:
        key: cg-qr-secret-prod
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mail-credentials
  namespace: circleguard-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: mail-credentials
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: cg-mail-password-prod
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: neo4j-credentials
  namespace: circleguard-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: neo4j-credentials
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: cg-neo4j-password-prod
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vault-secret
  namespace: circleguard-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: vault-secret
    creationPolicy: Owner
  data:
    - secretKey: secret
      remoteRef:
        key: cg-vault-secret-prod
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ldap-credentials
  namespace: circleguard-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: ldap-credentials
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: cg-ldap-password-prod
